##vishal_new.html

In [4]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup

In [2]:
with open('vishal_new.html','r',encoding='utf-8') as f:
    res=f.read()

In [4]:
soup=BeautifulSoup(res,'html.parser')

In [5]:
box=soup.find_all('div',class_='col col-7-12')
print(len(box))

24

In [6]:
d={"mobilename":[],
   "star":[],
  "reviews":[],
  "rating":[],
  "camera":[],
   "new_price":[],
  "old_price":[],
  "discount":[]}
box=soup.find_all('div',class_='_3pLy-c row')
print(len(box))
for i in box:
    d['mobilename'].append(i.find('div',class_='_4rR01T').text.strip())
    d['star'].append(i.find('div',class_='_3LWZlK').text.strip())
    d['reviews'].append(i.find('span',class_='_2_R_DZ').text.strip('&')[1])
    d['rating'].append(i.find('span',class_='_2_R_DZ').text.strip('&')[0])
    d['camera'].append(i.find('li',class_='rgWa7D').text.strip())
    d['new_price'].append(i.find('div',class_='_30jeq3 _1_WHN1').text.strip())
    try:
        d['old_price'].append(i.find('div',class_='_3I9_wc _27UcVY').text.strip())
    except:
        d['old_price'].append("not found")
    try:
        d['discount'].append(i.find('div',class_='_3Ay6Sb').text.strip())
    except:
        d["discount"].append("not found")
d=pd.DataFrame(d)
d

24

,mobilename,star,reviews,rating,camera,new_price,old_price,discount
0,"Huawei P9 (Mystic Silver, 32 GB)",4.5,2,8,3 GB RAM | 32 GB ROM | Expandable Upto 128 GB,"₹39,999","₹40,999",2% off
1,"Huawei P9 (Prestige Gold, 32 GB)",4.5,2,8,3 GB RAM | 32 GB ROM | Expandable Upto 128 GB,"₹39,999","₹40,999",2% off
2,"SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128...",4.5,",",3,8 GB RAM | 128 GB ROM,"₹49,999","₹1,01,999",50% off
3,"SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)",4.3,",",4,8 GB RAM | 128 GB ROM,"₹44,999","₹95,999",53% off
4,"MOTOROLA Edge 30 Ultra (Interstellar Black, 25...",4.2,5,5,12 GB RAM | 256 GB ROM,"₹49,999","₹74,999",33% off
5,"MOTOROLA Edge 30 Ultra (Starlight White, 256 GB)",4.2,5,5,12 GB RAM | 256 GB ROM,"₹49,999","₹74,999",33% off
6,"SAMSUNG Galaxy A54 5G (Awesome Violet, 256 GB)",4.3,1,4,8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,"₹40,999","₹45,999",10% off
7,"OnePlus 8 (Glacial Green, 256 GB)",4.5,4,2,12 GB RAM | 256 GB ROM,"₹46,999","₹47,999",2% off
8,"SAMSUNG Galaxy S22 Plus 5G (Green, 128 GB)",4.5,",",3,8 GB RAM | 128 GB ROM,"₹49,999","₹1,01,999",50% off
9,"OnePlus 8 (Interstellar Glow, 256 GB)",4.5,4,2,12 GB RAM | 256 GB ROM,"₹47,349","₹47,999",1% off
10,"Mi 10T Pro (Cosmic Black, 128 GB)",4.2,",",3,8 GB RAM | 128 GB ROM,"₹38,849","₹47,999",19% off
11,"SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)",4.3,",",4,8 GB RAM | 128 GB ROM,"₹44,999","₹95,999",53% off
12,"vivo X70 Pro (Cosmic Black, 256 GB)",4.4,7,9,12 GB RAM | 256 GB ROM,"₹49,999","₹57,990",13% off
13,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.4,7,9,12 GB RAM | 256 GB ROM,"₹47,999","₹57,990",17% off
14,"OnePlus 9RT 5G (Hacker Black, 256 GB)",4.1,7,2,12 GB RAM | 256 GB ROM,"₹48,999",not found,not found
15,"OnePlus 9RT 5G (Nano Silver, 256 GB)",4.1,7,2,12 GB RAM | 256 GB ROM,"₹46,999",not found,not found
16,"OnePlus 9 5G (Winter Mist, 256 GB)",4,8,2,12 GB RAM | 256 GB ROM,"₹49,999",not found,not found
17,"APPLE iPhone 11 (Red, 128 GB)",4.6,",",1,128 GB ROM,"₹46,999","₹48,900",3% off
18,"OnePlus 9 5G (Astral Black, 128 GB)",3.9,6,3,8 GB RAM | 128 GB ROM,"₹49,999",not found,not found
19,"Xiaomi 12 Pro 5G (Opera Mauve, 256 GB)",4.2,4,2,8 GB RAM | 256 GB ROM,"₹43,990","₹79,990",45% off
20,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.2,4,2,8 GB RAM | 256 GB ROM,"₹43,900","₹79,990",45% off
21,"realme GT 2 Pro (Steel Black, 128 GB)",4.2,",",2,8 GB RAM | 128 GB ROM,"₹49,999","₹57,999",13% off
22,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.5,",",3,8 GB RAM | 256 GB ROM,"₹48,999","₹54,990",10% off
23,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.1,1,2,12 GB RAM | 256 GB ROM,"₹48,880","₹84,999",42% off

In [7]:
with open('List of state and union territory capitals in India - Wikipedia (5_28_2025 8：46：50 AM).html','r',encoding='utf-8') as f:
    res=f.read()

In [8]:
soup=BeautifulSoup(res,'html.parser')

In [9]:
table=soup.find('table',class_='wikitable sortable jquery-tablesorter')
col_name=table.find('thead')
col=[]
for i in col_name.find_all('th'):
    col.append(i.text.strip())
col[5]=col[5][:col[5].find("\n")]

rows=table.find('tbody')
d={col[0]:[],col[1]:[],col[2]:[],col[3]:[],col[4]:[],col[5]:[]}
for i in rows.find_all('tr'):
    l=i.find_all('td')[0:5]
    d[col[0]].append(l[0].text.strip())
    d[col[1]].append(l[1].text.strip())
    d[col[2]].append(l[2].text.strip())
    d[col[3]].append(l[3].text.strip())
    d[col[4]].append(l[4].text.strip())
    try:
        d[col[5]].append(l[5].text.strip())
    except:
         d[col[5]].append("not found")
    
d=pd.DataFrame(d)
d

,State,Administrative/Executive capital,Legislative capital,Judicial capital,Year ofestablishment,Former capital
0,Andhra Pradesh,Amaravati,Amaravati,Amaravati,1956,not found
1,Arunachal Pradesh,Itanagar,Itanagar,Guwahati,1987,not found
2,Assam,Dispur,Dispur,Guwahati,1972,not found
3,Bihar,Patna,Patna,Patna,1950,not found
4,Chhattisgarh,Raipur[c],Raipur,Bilaspur,2000,not found
5,Goa,Panaji[d],Porvorim,Mumbai,1987,not found
6,Gujarat,Gandhinagar,Gandhinagar,Ahmedabad,1960,not found
7,Haryana,Chandigarh,Chandigarh,Chandigarh,1966,not found
8,Himachal Pradesh,Shimla,Shimla (Summer)Dharamshala (Winter)[5],Shimla,1971,not found
9,Jharkhand,Ranchi,Ranchi,Ranchi,2000,not found
10,Karnataka,Bengaluru,Bengaluru (Summer)Belgaum (Winter),Bengaluru,1956,not found
11,Kerala,Thiruvananthapuram,Thiruvananthapuram,Kochi[6],1956,not found
12,Madhya Pradesh,Bhopal,Bhopal,Jabalpur,1956,not found
13,Maharashtra,Mumbai[e],Mumbai (Summer)Nagpur (Winter),Mumbai,1960,not found
14,Manipur,Imphal,Imphal,Imphal,1972,not found
15,Meghalaya,Shillong,Shillong,Shillong,1972,not found
16,Mizoram,Aizawl,Aizawl,Guwahati,1987,not found
17,Nagaland,Kohima,Kohima,Guwahati,1963,not found
18,Odisha,Bhubaneswar,Bhubaneswar,Cuttack,1950,not found
19,Punjab,Chandigarh,Chandigarh,Chandigarh,1966,not found
20,Rajasthan,Jaipur,Jaipur,Jodhpur,1950,not found
21,Sikkim,Gangtok[f],Gangtok,Gangtok,1975,not found
22,Tamil Nadu,Chennai[g],Chennai,Chennai,1956,not found
23,Telangana,Hyderabad,Hyderabad,Hyderabad,2014,not found
24,Tripura,Agartala,Agartala,Agartala,1972,not found
25,Uttar Pradesh,Lucknow,Lucknow,Prayagraj,1950,not found
26,Uttarakhand,Dehradun,Bhararisain (summer)[8]Dehradun (winter),Nainital,2000,not found
27,West Bengal,Kolkata,Kolkata,Kolkata,1950,not found

In [5]:
with open('demo.html','r',encoding='utf-8') as f:
    res=f.read()

In [6]:
soup=BeautifulSoup(res,'html.parser')

user->request->view
python -m venv (venv name) to make venv
to start project python -m django startproject L1
in l1 python manage.py startapp app1
app1->view.py

In [81]:
d1={"name":[],
   "ROM":[],
  "RAM":[],
  "color":[],
  "Stars":[],
   "Reviews":[],
  "Rear Camera":[],
  "Front Camera":[],
    "old_price":[],
   "new_price":[],
  "discount":[],
   "rating":[],
   "display(cm)":[],
   "display(inch)":[]}
box=soup.find_all('div',class_='yKfJKb row')
print(len(box))
for i in box:
    d1['name'].append(i.find('div',class_='KzDlHZ').text.strip().split("(")[0])
    # d1['ROM'].append(i.find('li',class_='J+igdf').text.strip()).split('|')[1]
    d1['color'].append(i.find('div',class_='KzDlHZ').text.strip().split("(")[1].split(",")[0])
    d1['Stars'].append(i.find('div',class_='XQDdHH').text.strip())
    d1['Reviews'].append(i.find('span',class_='Wphh3N').text.strip().split("&")[1][1:].split("R")[0])
    d1['rating'].append(i.find('span',class_='Wphh3N').text.strip().split("&")[0][:-2].split(' ')[0].replace(",",""))
    d1['Rear Camera'].append(i.find('ul',class_='G4BRas').find_all('li')[2].text.strip().split("|")[0])
    d1['Front Camera'].append(i.find('ul',class_='G4BRas').find_all('li')[2].text.strip().split("|")[1].split("F")[0])
    d1['old_price'].append(i.find('div',class_='Nx9bqj _4b5DiR').text.strip().split("₹")[1].replace(",",""))
    try:
        d1['new_price'].append(i.find('div',class_='yRaY8j ZYYwLA').text.strip().split("₹")[1].replace(",",""))
    except:
        d1['new_price'].append('Nan')
    try:
        d1['discount'].append(i.find('div',class_='UkUFwK').text.strip().split(' ')[0])
    except:
        d1['discount'].append('NAn')
    d1['display(cm)'].append(i.find('ul',class_='G4BRas').find_all('li')[1].text.strip().split(" ")[0])
    d1['display(inch)'].append(i.find('ul',class_='G4BRas').find_all('li')[1].text.strip().split("(")[1].split(" ")[0])
    d1['ROM'].append(i.find('ul',class_='G4BRas').find_all('li')[0].text.strip().split("|")[1].split("R")[0])
    d1['RAM'].append(i.find('ul',class_='G4BRas').find_all('li')[0].text.strip().split("|")[0].split("R")[0])



    




df=pd.DataFrame(d1)
df

24

,name,ROM,RAM,color,Stars,Reviews,Rear Camera,Front Camera,old_price,new_price,discount,rating,display(cm),display(inch)
0,Google Pixel 7,128 GB,8 GB,Snow,4.3,"2,089",50MP + 12MP,10.8MP,30999,59999,48%,18882,16.0,6.3
1,Google Pixel 9A,256 GB,8 GB,Obsidian,4.5,123,48MP + 12MP,12MP,49999,Nan,NAn,1014,15.96,6.285
2,Google Pixel 8a,128 GB,8 GB,Obsidian,4.3,517,64MP + 13MP,13MP,37999,52999,28%,6056,15.49,6.1
3,Google Pixel 9A,256 GB,8 GB,Iris,4.5,123,48MP + 12MP,12MP,49999,Nan,NAn,1014,15.96,6.285
4,Google Pixel 7,128 GB,8 GB,Lemongrass,4.3,"2,089",50MP + 12MP,10.8MP,30999,59999,48%,18882,16.0,6.3
5,Google Pixel 8a,128 GB,8 GB,Porcelain,4.3,517,64MP + 13MP,13MP,37999,52999,28%,6056,15.49,6.1
6,Google Pixel 9A,256 GB,8 GB,Porcelain,4.5,123,48MP + 12MP,12MP,49999,Nan,NAn,1014,15.96,6.285
7,Google Pixel 7a,128 GB,8 GB,Charcoal,4.1,"2,685",64MP (OIS) + 13MP,13MP,27999,43999,36%,27130,15.49,6.1
8,Google Pixel 8a,128 GB,8 GB,Aloe,4.3,517,64MP + 13MP,13MP,37999,52999,28%,6056,15.49,6.1
9,Google Pixel 8a,128 GB,8 GB,Bay,4.3,517,64MP + 13MP,13MP,37999,52999,28%,6056,15.49,6.1
10,Google Pixel 7a,128 GB,8 GB,Snow,4.1,"2,685",64MP (OIS) + 13MP,13MP,27999,43999,36%,27130,15.49,6.1
11,Google Pixel 8,128 GB,8 GB,Rose,4.4,"1,428",50MP + 12MP,10.5MP,44999,75999,40%,18472,15.75,6.2
12,Google Pixel 7a,128 GB,8 GB,Sea,4.1,"2,685",64MP (OIS) + 13MP,13MP,27999,43999,36%,27130,15.49,6.1
13,Google Pixel 8a,256 GB,8 GB,Obsidian,4.3,517,64MP + 13MP,13MP,44999,59999,25%,6056,15.49,6.1
14,Google Pixel 9 Pro Fold,256 GB,16 GB,Obsidian,4.5,12,48MP + 10.5MP + 10.8MP,10MP,152999,172999,11%,132,16.0,6.3
15,Google Pixel 9 Pro,256 GB,16 GB,Hazel,4.6,58,50MP + 48MP + 48MP,42MP,89999,109999,18%,430,16.0,6.3
16,Google Pixel 8 Pro,128 GB,12 GB,Obsidian,4.4,119,50MP + 48MP + 48MP,10.5MP,59999,106999,43%,1069,17.02,6.7
17,Google Pixel 8 Pro,128 GB,12 GB,Bay,4.4,119,50MP + 48MP + 48MP,10.5MP,59999,106999,43%,1069,17.02,6.7
18,Google Pixel 8,128 GB,8 GB,Hazel,4.4,"1,428",50MP + 12MP,10.5MP,44999,75999,40%,18472,15.75,6.2
19,Google Pixel 9 Pro,256 GB,16 GB,Porcelain,4.6,58,50MP + 48MP + 48MP,42MP,89999,109999,18%,430,16.0,6.3
20,Google Pixel 9 Pro XL,512 GB,16 GB,Obsidian,4.6,60,50MP + 48MP + 48MP,42MP,119999,139999,14%,696,17.27,6.8
21,Google Pixel 9,256 GB,12 GB,Peony,4.6,293,50MP + 48MP,10.5MP,74999,79999,6%,2883,16.0,6.3
22,Google Pixel 9,256 GB,12 GB,Obsidian,4.6,293,50MP + 48MP,10.5MP,74999,79999,6%,2883,16.0,6.3
23,Google Pixel 6a,128 GB,6 GB,Chalk,4.3,"8,533",12.2MP + 12MP,8MP,43989,43999,NAn,75575,15.6,6.14

In [19]:
box[0].find('div',class_='KzDlHZ').text.strip().split("(")[1].split(",")[0]

'Snow'